-- Cleanup script for Replication Cost Calculator demo
USE ROLE ACCOUNTADMIN;

ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.REPLICATION_CALC.PRICING_REFRESH_TASK
  SUSPEND;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.REPLICATION_CALC.PRICING_REFRESH_TASK;

DROP STREAMLIT IF EXISTS REPLICATION_CALCULATOR;

DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.REPLICATION_CALC CASCADE;

DROP WAREHOUSE IF EXISTS SFE_REPLICATION_CALC_WH;
